[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter = "pExcmMBLztfuENuvZbN7MmbpG1yV93hMcMz9t1Y7Tyh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/quanghuy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
